### ISSUE TITLE
Fork probonopd/AppImages

### ISSUE THREAD

**Issue by probonopd** [fusion809/AppImages#1]
Thanks for forking the AppImages project. Unfortunately it looks like GitHub didn't get that this is a fork. To fix that: Please delete this repository on GitHub, then fork https://github.com/probonopd/AppImages using the fork button on GitHub, then make your changes therein. This way you preserve history and it will be much easier to incorporate your changes back to the original repository.

**Comment by fusion809** [comment]
I have no intention of making a pull request with the original. I created this because I want to experiment with this repo a little.

**Comment by probonopd** [comment]
Generally speaking, that's still what the fork button is for :-)
