### ISSUE TITLE
emacs does not work

### ISSUE THREAD

**Issue by probonopd** [fusion809/AppImages#2]
On Ubuntu 16.04:

```
me@host:~$ chmod a+x /home/me/Downloads/emacs-snapshot-201609270836-x86_64.AppImage 
me@host:~$ /home/me/Downloads/emacs-snapshot-201609270836-x86_64.AppImage 
Error: Error executing 'emacs'; return code: -1
```

Also, if you use Xenial ingredients, then your AppImage will not run on target systems older than Xenial.

**Comment by fusion809** [comment]
True, but using Trusty ingredients gives the error I reported on your [repo #94](https://github.com/probonopd/AppImages/issues/94) namely:

``` bash
out/emacs-snapshot-201609240437-x86_64.AppImage: ./lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by
/usr/lib/libMagickWand-6.Q16HDRI.so.2)
out/emacs-snapshot-201609240437-x86_64.AppImage: ./lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by
/usr/lib/libMagickCore-6.Q16HDRI.so.2)
out/emacs-snapshot-201609240437-x86_64.AppImage: ../lib/x86_64-linux-gnu/libgpg-error.so.0: no version information available (re
quired by /usr/lib/libgcrypt.so.20)
```

**Comment by probonopd** [comment]
Then you will run into the same issue once a newer distribution comes with a newer `/usr/lib/libMagic...`. You need to fix this in the recipe by bundling ImageMagick, it seems. Although I have no clue why a text editor might need it.

On a somewhat unrelated note, my guess is that we won't get a working AppImage without the support of upstream developers. But GNU people seem to care only about source code and not about binaries that "just work", so it might be a futile effort. I am using text editors and IDEs like Atom, KDevelop, Brackets instead.

**Comment by fusion809** [comment]
True. All GNU Project software is released solely as source code to my knowledge, for example, I like the GNU Octave scientific computing environment too, but they only provide source code tarballs for it.

**Comment by fusion809** [comment]
OK. I just uploaded a new AppImage (https://github.com/fusion809/AppImages/releases/tag/emacs-20160927-rev2) that seems to be working and is built from Trusty sources, using the new [Recipe](https://github.com/fusion809/AppImages/blob/fcf11655026b1f2c65d5c028fc13ed24e72dd0ee/recipes/emacs-snapshot/Recipe) as of commit [#fcf1165](https://github.com/fusion809/AppImages/commit/fcf11655026b1f2c65d5c028fc13ed24e72dd0ee). Please do give it a try and see if it works for you.

**Comment by probonopd** [comment]
Still

```
me@host:~$ /home/me/Downloads/emacs-snapshot-201609270836-x86_64.AppImage 
Error: Error executing 'emacs'; return code: -1
```

**Comment by fusion809** [comment]
Any ideas of how to debug this problem? For me it works fine, which may indicate that it's using my system's libraries and not just it's own.

**Comment by probonopd** [comment]
You should _test_ your AppImages, e.g., on a Ubuntu Live ISO.

**Comment by fusion809** [comment]
Yeah, but I don't see how that'll tell me the exact problem. Like sure that's a good idea before I upload my AppImages, to check that they're working, but I don't think that'll tell me much beyond the fact isn't working. Unless there's a way to make the error message more verbose than the one you just reported.

**Comment by probonopd** [comment]
`strace -eopen -f ./AppRun` inside the AppDir shows you which files it tries (or doesn't try) to access.
`LD_LIBRARY_DEBUG=libs ./AppRun` can help diagnose library issues.

**Comment by fusion809** [comment]
The output of strace was truly massive and bewildering to me http://paste2.org/bdG7Facg. It seems to be calling on libraries outside of the AppDir, if I'm reading the output correctly.

**Comment by probonopd** [comment]
Now you have a lot of work ahead of you - decide for which libraries it is ok to come from the outside vs. which libraries you need to bundle. Typically this involves intimate knowledge about how the app you are bundling works. Hence I was suggesting that the upstream software authors should do the AppImage, like, e.g.,  KDevelop does.
