### ISSUE TITLE
The same Recipe should run all the yml files

### ISSUE THREAD

**Issue by probonopd** [fusion809/AppImages#4]
The same Recipe should run all the yml files. Please don't duplicate it. Makes debugging much harder if so many versions are floating around. Is also spamming GitHub search results...

**Comment by fusion809** [comment]
I do so mostly because it saves me having to re-download it every time I git clone this repo. Plus sometimes the Recipes have to be altered due to a lack of metadata. So I can't just add to .gitignore recipes/meta/*/Recipe because some of those recipes are not present anywhere else.

**Comment by probonopd** [comment]
> sometimes the Recipes have to be altered due to a lack of metadata

Please don't, it will be an unmaintainable mess. Just store it once in your repo but not another copy of it for each app.
